### PR TITLE
Fix user agent strings

### LINKED ISSUE #112: Add tests that the user agent string is set correctly for traces & metrics
See comment: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/105#pullrequestreview-502680035

### PR DESCRIPTION
**Pull request by jsuereth**
- [X] Ensure user agent string is correct in Trace Exporter
- [X] Add user agent string test for trace exporter
- [x] Add user agent string test for metrics exporter.

Fixes #112

### CODE REVIEW

File: exporter/metric/metric_test.go [hunk 1]
```diff
@@ -422,3 +429,76 @@ func TestTimeIntervalPassthru(t *testing.T) {
...
+
+	exporter, err := NewRawExporter(opts...)
+	if err != nil {
+		t.Errorf("Error occurred when creating exporter: %v", err)
+	}
+
+	err = exporter.Export(ctx, cps)
+	assert.NoError(t, err)
+
+	// Now check for user agent string in the buffer from one call.
```
Comment (punya) [inline exporter/metric/metric_test.go:501]: Is this missing a check for the other call?

File: exporter/metric/metric_test.go [hunk 2]
```diff
@@ -422,3 +429,76 @@ func TestTimeIntervalPassthru(t *testing.T) {
...
+func (m *mock) CreateMetricDescriptor(ctx context.Context, req *monitoringpb.CreateMetricDescriptorRequest) (*googlemetricpb.MetricDescriptor, error) {
+	return m.createMetricDescriptor(ctx, req)
+}
+
+func TestExportMetricsWithUserAgent(t *testing.T) {
+	server := grpc.NewServer()
+	t.Cleanup(server.Stop)
+
+	// Channel to shove user agent strings into
+	ch := make(chan []string, 2)
```
Comment (punya) [inline exporter/metric/metric_test.go:452]: I assume this is allocated with length 2 so that you can save two calls into it, then check both. Consider interleaving the calls and checks instead -- it's a bit clearer to see that *each* call sets the UA properly. If you go that route, you can reduce the buffer to length 1.

**Review by punya — APPROVED** [review]

File: exporter/metric/metric_test.go (hunk 1 above)
Comment (jsuereth) [reply exporter/metric/metric_test.go:501]: Do you think there's value in checking both?   What're the odds you misconfigure JUST ONE grpc method user agent without misconfiguring both?

File: exporter/metric/metric_test.go (hunk 2 above)
Comment (jsuereth) [reply exporter/metric/metric_test.go:452]: I updated it to be as you state, I think the test is a bit less readable and I was a bit concerned about whether it flakily passes as I'm not sure how to know when a channel is "done" in Go without adding an explicit signal. I don't think there's a huge value in testing both UAs, but it's done :)
